version: '3.7'

services:
  db:
    image: mysql:5.7
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == manager
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wordpress

  wordpress:
    image: wordpress:latest
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == manager
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    networks:
      - wordpress

volumes:
  mysql_data:
  wordpress_data:

networks:
  wordpress:
    driver: overlay
